export const actionTypes = {
  TEST_FAILURE: 'FAILURE',
  TEST_INCREMENT: 'INCREMENT',
  TEST_DECREMENT: 'DECREMENT',
  TEST_RESET: 'RESET',
  TEST_LOAD_DATA: 'LOAD_DATA',
  TEST_LOAD_DATA_SUCCESS: 'LOAD_DATA_SUCCESS',
  TEST_START_CLOCK: 'START_CLOCK',
  TEST_TICK_CLOCK: 'TICK_CLOCK'
};
